### ISSUE TITLE
Terrain

### ISSUE THREAD

**Issue by neil-phan** [neil-phan/evolve#17]
Implement a noise generating algorithm to create a unique terrain for the organisms to travel in

Will include random patches of elevation and depression, where certain values of depression will mean a water source. Organisms will know the water source is necessary for survival and will flock towards it when needed.

Time permitting, modify organism's speed on different terrains. Spawn food more frequently or less frequently depending on the terrain.

**Comment by aliparslan** [comment]
Finished terrain, will work on speed after merging branches
